version: '3'
services:
  bot:
    build: 
      context: ./bot-mpsr
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
  
   
  api:
    build: 
      context: ./chatui
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - bot
      